language: r
sudo: required

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
  - doParallel
  - foreach
  - testthat
  
branches:
  only:
    - master

notifications:
  email:
    recipients:
    - landon.sego@pnnl.gov
    on_success: change
    on_failure: change
